### ISSUE TITLE
Implement Achievement tracking

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/SpaceAge#6]
The system should track achievements, in event handlers (E) or, rarely, FixedUpdate loops (U). Achievements are of three types: Max (M), Total (T), and First (F). For M and F achievements, time is also recorded.

Examples:
- [x] most expensive, heaviest, most complex rockets (EM)
- [x] max crew in a vessel (EM)
- [x] heaviest vessel in orbit, to land on another celestial body (U?M)
- [x] max number of astronauts on missions simultaneously (EM)
- [x] total funds and science earned (ET)
- [x] total number and mass of launched vessels (ET)
- [x] total crewed and uncrewed launches, total number of astronauts (ET)
- [x] first launch, reaching the space, orbit, and recovery, crewed and otherwise (EF)
- [x] first destroyed ship, first death (EF)
- [x] first flyby, orbit, landing on, return from a celestial body, crewed and otherwise (EF)

**Comment by GarwelGarwel** [comment]
Everything except vessel cost and simultaneous stuff implemented.

**Comment by GarwelGarwel** [comment]
Implemented most expensive launch and max simultaneous kerbals
